enabling general agenda
JavaDominicano/conference pull request #338
Opened 2024-05-10 04:39 UTC by ecabrerar

2024-05-10 04:48 UTC, BrayanMnz commented
Los workshops salen en el tab de sesiones. @ecabrerar

2024-05-10 05:56 UTC, BrayanMnz commented
Los workshops se muestran ahora en ambos tabs, pero en la de workshops no se ve la imagen del conferencista.

2024-05-10 05:57 UTC, BrayanMnz requested changes
En la ventana de Workshops, no se muestra imagen de conferencistas.

2024-05-10 13:49 UTC, fredpena requested changes
Las fotos de en los WorkShop no se ven, y en las secciones aparecen todos los WorkShop

Que vas ha pasar con los co-speaker, tu y diego, hay que agregar a los talleres para que se vea.

2024-05-24 13:21 UTC, BrayanMnz commented
@ecabrerar @fredpena debemos habilitar la agenda.

2024-05-27 19:19 UTC, merged